appium.server.url=http://127.0.0.1:4723/
platform.name=Android
platform.version=17
device.name=emulator-5554
app.package=com.example.dentzy
app.activity=com.example.dentzy.MainActivity
app.path=../dentzy/build/app/outputs/flutter-apk/app-debug.apk
automation.name=UiAutomator2
new.command.timeout=600
implicit.wait=10
explicit.wait=20
report.path=reports
screenshot.path=screenshots
log.path=logs
testdata.path=testdata
excel.report.name=AutomationResults.xlsx
extent.report.name=AutomationReport.html
